### PR TITLE
Add the ER swagger 2.0 api specification

### PR DESCRIPTION
**Pull request by m-linner-ericsson**
### Applicable Issues
https://github.com/eiffel-community/eiffel-remrem-generate/issues/175

### Description of the Change
Add the Swagger 2.0 specification of the ER 

### Alternate Designs
N/A

### Benefits
Give more information about the interface that REMReM communicates with

### Possible Drawbacks
N/A

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Mattias Linnér mattias.linner@ericsson.com

### CODE REVIEW

**Comment by t-persson** [comment]
I have continued the discussion on slack. But this helps us, if a compatibility layer is to be developed in EiffelGraphQLAPI

**Review by t-persson — APPROVED** [review]

**Review by magnusbaeck — COMMENTED** [review]
Wouldn't it make more sense to publish this API spec in https://github.com/eiffel-community/eiffel-event-repository? Documenting the API here seems backwards.

**Comment by tobiasake** [comment]
Yepp, I think also it should be added ER Github repository.

**Comment by m-linner-ericsson** [comment]
Please see https://github.com/eiffel-community/eiffel-event-repository/pull/11

**Comment by m-linner-ericsson** [comment]
@tobiasake @magnusbaeck @t-persson I have now moved this to the event repository instead

**Pull request closed without merging**
